package main

import (
	"context"
	"fmt"
	"os"
	"time"
	wwanmbim "github.com/damonto/wwan-go/mbim"
)
const ( device="/dev/wwan0mbim0"; esimSlot=2 )
func readyStateName(state wwanmbim.SubscriberReadyState) string { switch state { case wwanmbim.SubscriberReadyStateNotInitialized:return "not-initialized"; case wwanmbim.SubscriberReadyStateInitialized:return "initialized"; case wwanmbim.SubscriberReadyStateSIMNotInserted:return "sim-not-inserted"; case wwanmbim.SubscriberReadyStateBadSIM:return "bad-sim"; case wwanmbim.SubscriberReadyStateFailure:return "failure"; case wwanmbim.SubscriberReadyStateNotActivated:return "not-activated"; case wwanmbim.SubscriberReadyStateDeviceLocked:return "device-locked"; case wwanmbim.SubscriberReadyStateNoESIMProfile:return "no-esim-profile"; default:return "unknown" } }
func passThroughName(status wwanmbim.UiccPassThroughStatus) string { switch status { case wwanmbim.UiccPassThroughStatusDisabled:return "disabled"; case wwanmbim.UiccPassThroughStatusEnabled:return "enabled"; default:return "unknown" } }
func run()(err error){ ctx,cancel:=context.WithTimeout(context.Background(),90*time.Second); defer cancel(); client,err:=wwanmbim.Open(ctx,wwanmbim.WithProxy(device),wwanmbim.WithSlot(esimSlot)); if err!=nil{return fmt.Errorf("opening MBIM proxy for eSIM slot 2: %w",err)}; defer func(){if closeErr:=client.Close();err==nil&&closeErr!=nil{err=fmt.Errorf("closing MBIM client: %w",closeErr)}}(); version:=client.Version(); fmt.Printf("MBIM_VERSION_HEX=0x%04X\n",version.MBIMVersion); fmt.Printf("MBIMEX_VERSION_HEX=0x%04X\n",version.MBIMExVersion); fmt.Println("\n=== SUBSCRIBER READY STATUS — SLOT 2 ==="); for attempt:=1;attempt<=6;attempt++{status,e:=client.SubscriberReadyStatus(ctx);if e!=nil{fmt.Printf("READY_ATTEMPT_%d_ERROR=%v\n",attempt,e)}else{fmt.Printf("READY_ATTEMPT_%d_STATE=%s(%d)\n",attempt,readyStateName(status.ReadyState),status.ReadyState);fmt.Printf("READY_ATTEMPT_%d_FLAGS=0x%X\n",attempt,uint32(status.Flags));fmt.Printf("READY_ATTEMPT_%d_SLOT_ID=%d\n",attempt,status.SlotID);if status.ReadyState==wwanmbim.SubscriberReadyStateInitialized||status.ReadyState==wwanmbim.SubscriberReadyStateNoESIMProfile{break}};if attempt<6{time.Sleep(3*time.Second)}}; fmt.Println("\n=== UICC PASSTHROUGH STATUS — SLOT 2 ==="); pass,e:=client.QueryUiccReset(ctx);if e!=nil{fmt.Printf("PASSTHROUGH_QUERY_ERROR=%v\n",e)}else{fmt.Printf("PASSTHROUGH_STATUS=%s(%d)\n",passThroughName(pass),pass)}; fmt.Println("\n=== UICC ATR — SLOT 2 ==="); atr,e:=client.QueryUiccATR(ctx);if e!=nil{fmt.Printf("ATR_QUERY_ERROR=%v\n",e)}else{fmt.Printf("ATR_LENGTH=%d\n",len(atr));fmt.Printf("ATR_HEX=%X\n",atr)}; fmt.Println("\n=== TERMINAL CAPABILITY — SLOT 2 ==="); caps,e:=client.QueryUiccTerminalCapability(ctx);if e!=nil{fmt.Printf("TERMINAL_CAPABILITY_QUERY_ERROR=%v\n",e)}else{fmt.Printf("TERMINAL_CAPABILITY_COUNT=%d\n",len(caps))}; return nil }
func main(){if err:=run();err!=nil{fmt.Fprintf(os.Stderr,"ERROR: %v\n",err);os.Exit(1)}}
