package main

import (
 "context"; "flag"; "fmt"; "io"; "log/slog"; "os"; "strings"; "time"
 euiccmbim "github.com/damonto/euicc-go/driver/mbim"
 "github.com/damonto/euicc-go/lpa"
 sgp22 "github.com/damonto/euicc-go/v2"
 wwanmbim "github.com/damonto/wwan-go/mbim"
)
const(device="/dev/wwan0mbim0";esimSlot=2)
func oneLine(v string)string{v=strings.ReplaceAll(v,"\r"," ");v=strings.ReplaceAll(v,"\n"," ");v=strings.TrimSpace(v);if len(v)>500{v=v[:500]+"..."};return v}
func mask(v string)string{v=strings.TrimSpace(v);if len(v)<=10{return strings.Repeat("*",len(v))};return v[:6]+strings.Repeat("*",len(v)-10)+v[len(v)-4:]}
func openClient(ctx context.Context)(*lpa.Client,error){raw,e:=wwanmbim.Open(ctx,wwanmbim.WithProxy(device),wwanmbim.WithSlot(esimSlot));if e!=nil{return nil,fmt.Errorf("opening MBIM proxy for eSIM slot 2: %w",e)};ch,e:=euiccmbim.NewWithClient(raw);if e!=nil{_ = raw.Close();return nil,fmt.Errorf("creating eUICC MBIM channel: %w",e)};quiet:=slog.New(slog.NewTextHandler(io.Discard,nil));c,e:=lpa.New(&lpa.Options{Channel:ch,Logger:quiet,Timeout:90*time.Second});if e!=nil{_ = ch.Disconnect();return nil,fmt.Errorf("opening eUICC ISD-R: %w",e)};return c,nil}
func listProfiles(c *lpa.Client)([]*sgp22.ProfileInfo,error){var last error;for a:=1;a<=5;a++{p,e:=c.ListProfile(nil,nil);if e==nil{return p,nil};last=e;if a<5{time.Sleep(2*time.Second)}};return nil,last}
func expectedProfile(c *lpa.Client)(*sgp22.ProfileInfo,error){p,e:=listProfiles(c);if e!=nil{return nil,fmt.Errorf("listing profiles: %w",e)};fmt.Printf("PROFILE_COUNT=%d\n",len(p));if len(p)!=1{return nil,fmt.Errorf("expected exactly one profile for this conservative helper, found %d; use a full LPA when multiple profiles are installed",len(p))};x:=p[0];fmt.Printf("PROFILE_NAME=%s\n",oneLine(x.ProfileName));fmt.Printf("PROFILE_PROVIDER=%s\n",oneLine(x.ServiceProviderName));fmt.Printf("PROFILE_ICCID_MASKED=%s\n",mask(x.ICCID.String()));fmt.Printf("PROFILE_CLASS=%s\n",x.ProfileClass.String());fmt.Printf("PROFILE_STATE=%s\n",x.ProfileState.String());if x.ProfileClass.String()!="operational"{return nil,fmt.Errorf("profile class is %q, expected operational",x.ProfileClass.String())};return x,nil}
func status()error{ctx,cancel:=context.WithTimeout(context.Background(),3*time.Minute);defer cancel();c,e:=openClient(ctx);if e!=nil{return e};defer c.Close();_,e=expectedProfile(c);return e}
func enable()error{ctx,cancel:=context.WithTimeout(context.Background(),3*time.Minute);defer cancel();c,e:=openClient(ctx);if e!=nil{return e};defer c.Close();p,e:=expectedProfile(c);if e!=nil{return e};s:=p.ProfileState.String();if s=="enabled"{fmt.Println("PROFILE_ENABLE_ALREADY=yes");return nil};if s!="disabled"{return fmt.Errorf("profile state is %q, expected disabled",s)};fmt.Println("PROFILE_ENABLE_REQUEST=starting");if e:=c.EnableProfile(p.ICCID,true);e!=nil{return fmt.Errorf("enabling profile: %w",e)};fmt.Println("PROFILE_ENABLE_REQUEST=accepted");return nil}
func notifications()error{ctx,cancel:=context.WithTimeout(context.Background(),3*time.Minute);defer cancel();c,e:=openClient(ctx);if e!=nil{return e};defer c.Close();if _,e:=expectedProfile(c);e!=nil{return e};p,e:=c.RetrieveNotificationList(nil);if e!=nil{return fmt.Errorf("retrieving notifications: %w",e)};fmt.Printf("PENDING_NOTIFICATION_COUNT=%d\n",len(p));for _,i:=range p{if i==nil||i.Notification==nil{continue};s:=i.Notification.SequenceNumber;if e:=c.HandleNotification(i);e!=nil{return fmt.Errorf("sending notification %d: %w",s,e)};if e:=c.RemoveNotificationFromList(s);e!=nil{return fmt.Errorf("removing notification %d: %w",s,e)};fmt.Printf("NOTIFICATION_%d=sent-and-removed\n",s)};return nil}
func main(){a:=flag.String("action","status","status, enable, or notifications");flag.Parse();var e error;switch *a{case"status":e=status();case"enable":e=enable();case"notifications":e=notifications();default:e=fmt.Errorf("unknown action %q",*a)};if e!=nil{fmt.Fprintf(os.Stderr,"ERROR: %s\n",oneLine(e.Error()));os.Exit(1)}}
