package main

import("bytes";"context";"fmt";"os";"strings";"time";wwanmbim "github.com/damonto/wwan-go/mbim")
const(device="/dev/wwan0mbim0";esimSlot=2)
func passName(s wwanmbim.UiccPassThroughStatus)string{if s==wwanmbim.UiccPassThroughStatusEnabled{return"enabled"};if s==wwanmbim.UiccPassThroughStatusDisabled{return"disabled"};return"unknown"}
func same(a,b [][]byte)bool{if len(a)!=len(b){return false};for i:=range a{if !bytes.Equal(a[i],b[i]){return false}};return true}
func save(path string,caps [][]byte)error{var b strings.Builder;for i,c:=range caps{fmt.Fprintf(&b,"CAPABILITY_%d=%X\n",i,c)};return os.WriteFile(path,[]byte(b.String()),0o600)}
func run()(err error){if len(os.Args)!=2{return fmt.Errorf("usage: %s CAPABILITY_OUTPUT_FILE",os.Args[0])};ctx,cancel:=context.WithTimeout(context.Background(),180*time.Second);defer cancel();c,e:=wwanmbim.Open(ctx,wwanmbim.WithProxy(device),wwanmbim.WithSlot(esimSlot));if e!=nil{return fmt.Errorf("opening MBIM proxy for eSIM slot 2: %w",e)};defer func(){if ce:=c.Close();err==nil&&ce!=nil{err=ce}}();v:=c.Version();fmt.Printf("MBIMEX_VERSION_HEX=0x%04X\n",v.MBIMExVersion);if v.MBIMExVersion<0x0400{return fmt.Errorf("MBIMEx 4.0 is required; modem negotiated 0x%04X",v.MBIMExVersion)};p,e:=c.QueryUiccReset(ctx);if e!=nil{return e};fmt.Printf("PASSTHROUGH_BEFORE=%s(%d)\n",passName(p),p);if p==wwanmbim.UiccPassThroughStatusEnabled{if _,e=c.SetUiccReset(ctx,wwanmbim.UiccPassThroughActionDisable);e!=nil{return fmt.Errorf("disabling passthrough: %w",e)};time.Sleep(4*time.Second)};caps,e:=c.QueryUiccTerminalCapability(ctx);if e!=nil{return fmt.Errorf("querying terminal capabilities: %w",e)};if len(caps)==0{return fmt.Errorf("modem returned zero terminal capability objects")};fmt.Printf("TERMINAL_CAPABILITY_COUNT=%d\n",len(caps));for i,x:=range caps{fmt.Printf("TERMINAL_CAPABILITY_%d_HEX=%X\n",i,x)};if e=save(os.Args[1],caps);e!=nil{return e};if e=c.SetUiccTerminalCapability(ctx,caps);e!=nil{return fmt.Errorf("setting terminal capabilities: %w",e)};verify,e:=c.QueryUiccTerminalCapability(ctx);if e!=nil{return e};if !same(caps,verify){return fmt.Errorf("terminal capability verification mismatch")};fmt.Println("TERMINAL_CAPABILITY_VERIFY=match");if _,e=c.SetUiccReset(ctx,wwanmbim.UiccPassThroughActionDisable);e!=nil{return fmt.Errorf("resetting eSIM in normal mode: %w",e)};atr,e:=c.QueryUiccATR(ctx);if e!=nil{return fmt.Errorf("querying ATR after normal reset: %w",e)};fmt.Printf("ATR_LENGTH=%d\n",len(atr));fmt.Println("SLOT2_INITIALIZATION=complete");return nil}
func main(){if e:=run();e!=nil{fmt.Fprintf(os.Stderr,"ERROR: %v\n",e);os.Exit(1)}}
